# Generated by Django 4.2.7 on 2023-11-30 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_planilla', models.IntegerField()),
                ('monto_inicial', models.FloatField()),
                ('monto_final', models.FloatField()),
                ('hora_inicio', models.TimeField(auto_now_add=True)),
                ('hora_fin', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campanas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cam', models.CharField(max_length=20)),
                ('nombre_cam', models.CharField(max_length=20)),
                ('descripcion_camp', models.TextField()),
                ('monto_cam', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cli', models.CharField(max_length=20)),
                ('apellido_cli', models.CharField(max_length=20)),
                ('dni_cli', models.IntegerField(verbose_name=9)),
                ('cuit_cli', models.IntegerField(verbose_name=13)),
                ('tel_cli', models.IntegerField(verbose_name=22)),
                ('dom_cli', models.CharField(max_length=40)),
                ('email_cli', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_emp', models.CharField(max_length=20)),
                ('apellido_emp', models.CharField(max_length=20)),
                ('dni_emp', models.IntegerField(verbose_name=9)),
                ('tel_emp', models.IntegerField(verbose_name=22)),
                ('dom_emp', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Medios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medio', models.CharField(max_length=50)),
                ('empresa_medio', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prov', models.CharField(max_length=20)),
                ('apellido_prov', models.CharField(max_length=20)),
                ('dni_prov', models.IntegerField(verbose_name=9)),
                ('cuit_prov', models.IntegerField(verbose_name=13)),
                ('tel_prov', models.IntegerField(verbose_name=22)),
                ('dom_prov', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_De_Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.campanas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.clientes')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prod', models.CharField(max_length=50)),
                ('precio_prod', models.FloatField()),
                ('cantidad_prod', models.IntegerField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_fact', models.CharField(max_length=20)),
                ('fecha_fact', models.DateField(auto_now_add=True)),
                ('mont_fact', models.FloatField()),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.cajas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.contratos')),
                ('nro_factura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.facturas')),
            ],
        ),
        migrations.AddField(
            model_name='contratos',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.tipo_de_contrato'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.ventas'),
        ),
        migrations.CreateModel(
            name='Camxmed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(auto_now=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.campanas')),
                ('medio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.medios')),
            ],
        ),
        migrations.AddField(
            model_name='campanas',
            name='productos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.productos'),
        ),
        migrations.AddField(
            model_name='cajas',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.empleados'),
        ),
    ]
