# Generated by Django 4.2.7 on 2023-12-09 22:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrepago', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=40)),
                ('dni', models.CharField(max_length=9)),
                ('num_tarjeta', models.CharField(max_length=16)),
                ('codigo_seg', models.CharField(max_length=3)),
                ('vencimiento', models.CharField(max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='user_cli',
        ),
        migrations.AlterField(
            model_name='campanas',
            name='productos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.productos'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cuit_cli',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='dni_cli',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tel_cli',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='dni_emp',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='tel_emp',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='cuit_prov',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='dni_prov',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='tel_prov',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.clientes'),
        ),
        migrations.CreateModel(
            name='FacturaFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_facfin', models.DateField(auto_now_add=True)),
                ('hora_facfin', models.TimeField(auto_now_add=True)),
                ('campanaeleg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.campanas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.clientes')),
            ],
        ),
        migrations.AddField(
            model_name='detalles',
            name='forma_pago',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.formapago'),
            preserve_default=False,
        ),
    ]
